# Generated by Django 3.2.5 on 2021-09-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['image_name']},
        ),
        migrations.AddField(
            model_name='images',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.FileField(upload_to='galery/static/galery/img/'),
        ),
    ]
